import Head from 'next/head'
import React, { useState } from 'react';
import styles from '../styles/Home.module.css'
import { Canvas } from "@react-three/fiber";
import Box from "../components/Box";
import LightBulb from "../components/LightBulb";
import Floor from "../components/Floor";
import OrbitControls from "../components/OrbitControls";
import Draggable from "../components/Draggable";
import Model from "../components/Model";
import Light from "../components/Light";
export default function Home() {
  const [active, setActive] = useState(false)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Render 3.js scene in Next App
        </h1>
        <div className={styles.scene}>
          <Canvas
            shadows={true}
            className={styles.canvas}
            camera={{
              position: [-6, 7, 7],
            }}
          >
            <ambientLight color='red' intensity={0.3}/>
            <LightBulb position={[0, 3, 0]} />
            <Draggable>
              <Box rotateX={3} rotateY={0.2} />
            </Draggable>
            <OrbitControls />
            <Floor position={[0, -1, 0]} />
          </Canvas>
        </div>

        <h1 className={styles.title}>
          Render Clickable button inside 3js
        </h1>

        <p>This part is a React component, the below sketch is {active ? 'inactive' : 'active'}</p>

        <Canvas>
          <mesh scale={active ? 1 : 1.5} onClick={() => setActive(!active)} >
            <boxGeometry color={active ? 'red' : 'green'}/>
            <meshBasicMaterial color={active ? 'red' : 'green'} />
          </mesh>
        </Canvas>

        <h1 className={styles.title}>
          Render Blender file inside 3.js
        </h1>

        {/* GLTF, FBX and OBJ. All of these will use the useLoader function but in slightly different ways. */}
        <Canvas camera={{ position: [0, 0, 150] }}>
          <ambientLight color={active ? 'red' : 'yellow'}  intensity={0.7}/>
          <Model/>
        </Canvas>
      </main>
    </div>
  )
}
